apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs-pod
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      name: openmrs-application
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 25%
       maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: openmrs-application
    spec:
      containers:
        - image: krishnatester/openmrs:2.0
          name: openmrs-deployment
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
           - name: MYSQL_ROOT_PASSWORD
             value: 'rootroot'
           - name: MYSQL_DATABASE
             value: 'gameoflife'
           - name: MYSQL_USER
             value: qtdevops
           - name: MYSQL_PASSWORD
             value: qtdevops
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          livenessProbe:
             httpGet:
               path: /openmrs
               port: 35000
             initialDelaySeconds: 5
             periodSeconds: 10
          readinessProbe:
             tcpSocket:
               port: 35000
          