- name: installing_nodejs_centos
  become: yes
  hosts: all
  vars:
    package: nodejs
    url_path: https://rpm.nodesource.com/setup_{{version}}.x
    dest_path: /tmp/setup_{{version}}.x.sh
    version: "18"
  tasks:
  - name: downloading_nodejs
    ansible.builtin.get_url:
      url: "{{ url_path }}"
      dest: "{{ dest_path }}"
      mode: '777'
  - name: using_shell_command
    ansible.builtin.shell: "{{ dest_path }}"
  - name: installing_nodejs_centos
    ansible.builtin.yum:
      name: "{{ package }}"
      update_cache: yes
      state: present

