apiVersion: v1
kind: Pod
metadata:
  name: sql-pod
spec:
  containers:
    - name: nop-sql
      image: mysql:8
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume
      ports:
        - containerPort: 3600
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'rootroot'
        - name: MYSQL_DATABASE
          value: 'nop'
        - name: MYSQL_USER
          value: satya
        - name: MYSQL_PASSWORD
          value: satya
  volumes:
    - name: mysql-volume
      persistentVolumeClaim:
        claimName: nop-vol

