apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: nop-vol
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests: 
      storage: 1Gi
    