apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop-pod
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      name: nop-application
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        name: nop-application
    spec:
      containers:
      - image: krishnatester/nop:1.0
        name: nop-container
        livenessProbe:
          httpGet:
              path: /
              port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
           initialDelaySeconds: 5
           periodSeconds: 10
           tcpSocket:
             port: 80

        ports:
        - name: nop-port
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "1Gi"

