
  - name: spring_petclinic
    become: yes
    hosts: all
    tasks:
      - name: Copy file with owner and permissions
        ansible.builtin.copy:
          src: /home/sai/spring-petclinic.service
          dest: /etc/systemd/system/spring-petclinic.service
          mode: '644'
      - name: reload
        ansible.builtin.systemd:
          name: spring-petclinic.service
          state: started
          daemon_reload: true